<?php

declare(strict_types=1);

namespace App\DTOs\Meal;

final class MealDTO
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $uuid = null,
        public readonly ?string $mealCode = null,
        public readonly ?int $categoryId = null,
        public readonly ?int $mealTypeId = null,
        public readonly ?int $kitchenId = null,
        public readonly ?string $name = null,
        public readonly ?string $slug = null,
        public readonly ?string $shortDescription = null,
        public readonly ?string $description = null,
        public readonly ?array $ingredients = null,
        public readonly ?array $allergens = null,
        public readonly int $spiceLevel = 0,
        public readonly ?string $servingSize = null,
        public readonly ?string $unit = null,
        public readonly ?string $mealImage = null,
        public readonly ?string $thumbnail = null,
        public readonly ?array $gallery = null,
        public readonly ?string $barcode = null,
        public readonly ?string $sku = null,
        public readonly ?string $hsnCode = null,
        public readonly int $preparationTime = 0,
        public readonly float $calories = 0,
        public readonly float $protein = 0,
        public readonly float $carbohydrates = 0,
        public readonly float $fat = 0,
        public readonly float $fiber = 0,
        public readonly float $sugar = 0,
        public readonly float $sodium = 0,
        public readonly float $price = 0,
        public readonly ?float $offerPrice = null,
        public readonly ?float $costPrice = null,
        public readonly float $taxPercentage = 0,
        public readonly int $displayOrder = 0,
        public readonly string $availabilityType = 'all_day',
        public readonly ?array $availabilitySlots = null,
        public readonly bool $isFeatured = false,
        public readonly bool $isRecommended = false,
        public readonly bool $isNew = false,
        public readonly bool $isBestseller = false,
        public readonly bool $isCustomizable = false,
        public readonly bool $requiresPreparation = true,
        public readonly string $status = 'active',
        public readonly ?string $remarks = null,
        public readonly ?int $createdBy = null,
        public readonly ?int $updatedBy = null,
        public readonly ?int $deletedBy = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: isset($data['id']) ? (int) $data['id'] : null,
            uuid: $data['uuid'] ?? null,
            mealCode: $data['meal_code'] ?? null,
            categoryId: isset($data['category_id']) ? (int) $data['category_id'] : null,
            mealTypeId: isset($data['meal_type_id']) ? (int) $data['meal_type_id'] : null,
            kitchenId: isset($data['kitchen_id']) ? (int) $data['kitchen_id'] : null,
            name: $data['name'] ?? null,
            slug: $data['slug'] ?? null,
            shortDescription: $data['short_description'] ?? null,
            description: $data['description'] ?? null,
            ingredients: is_array($data['ingredients'] ?? null) ? $data['ingredients'] : (isset($data['ingredients']) ? json_decode($data['ingredients'], true) : null),
            allergens: is_array($data['allergens'] ?? null) ? $data['allergens'] : (isset($data['allergens']) ? json_decode($data['allergens'], true) : null),
            spiceLevel: isset($data['spice_level']) ? (int) $data['spice_level'] : 0,
            servingSize: $data['serving_size'] ?? null,
            unit: $data['unit'] ?? null,
            mealImage: $data['meal_image'] ?? null,
            thumbnail: $data['thumbnail'] ?? null,
            gallery: is_array($data['gallery'] ?? null) ? $data['gallery'] : (isset($data['gallery']) ? json_decode($data['gallery'], true) : null),
            barcode: $data['barcode'] ?? null,
            sku: $data['sku'] ?? null,
            hsnCode: $data['hsn_code'] ?? null,
            preparationTime: isset($data['preparation_time']) ? (int) $data['preparation_time'] : 0,
            calories: isset($data['calories']) ? (float) $data['calories'] : 0,
            protein: isset($data['protein']) ? (float) $data['protein'] : 0,
            carbohydrates: isset($data['carbohydrates']) ? (float) $data['carbohydrates'] : 0,
            fat: isset($data['fat']) ? (float) $data['fat'] : 0,
            fiber: isset($data['fiber']) ? (float) $data['fiber'] : 0,
            sugar: isset($data['sugar']) ? (float) $data['sugar'] : 0,
            sodium: isset($data['sodium']) ? (float) $data['sodium'] : 0,
            price: isset($data['price']) ? (float) $data['price'] : 0,
            offerPrice: isset($data['offer_price']) ? (float) $data['offer_price'] : null,
            costPrice: isset($data['cost_price']) ? (float) $data['cost_price'] : null,
            taxPercentage: isset($data['tax_percentage']) ? (float) $data['tax_percentage'] : 0,
            displayOrder: isset($data['display_order']) ? (int) $data['display_order'] : 0,
            availabilityType: $data['availability_type'] ?? 'all_day',
            availabilitySlots: is_array($data['availability_slots'] ?? null) ? $data['availability_slots'] : (isset($data['availability_slots']) ? json_decode($data['availability_slots'], true) : null),
            isFeatured: (bool) ($data['is_featured'] ?? false),
            isRecommended: (bool) ($data['is_recommended'] ?? false),
            isNew: (bool) ($data['is_new'] ?? false),
            isBestseller: (bool) ($data['is_bestseller'] ?? false),
            isCustomizable: (bool) ($data['is_customizable'] ?? false),
            requiresPreparation: (bool) ($data['requires_preparation'] ?? true),
            status: $data['status'] ?? 'active',
            remarks: $data['remarks'] ?? null,
            createdBy: isset($data['created_by']) ? (int) $data['created_by'] : null,
            updatedBy: isset($data['updated_by']) ? (int) $data['updated_by'] : null,
            deletedBy: isset($data['deleted_by']) ? (int) $data['deleted_by'] : null,
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'uuid' => $this->uuid,
            'meal_code' => $this->mealCode,
            'category_id' => $this->categoryId,
            'meal_type_id' => $this->mealTypeId,
            'kitchen_id' => $this->kitchenId,
            'name' => $this->name,
            'slug' => $this->slug,
            'short_description' => $this->shortDescription,
            'description' => $this->description,
            'ingredients' => $this->ingredients,
            'allergens' => $this->allergens,
            'spice_level' => $this->spiceLevel,
            'serving_size' => $this->servingSize,
            'unit' => $this->unit,
            'meal_image' => $this->mealImage,
            'thumbnail' => $this->thumbnail,
            'gallery' => $this->gallery,
            'barcode' => $this->barcode,
            'sku' => $this->sku,
            'hsn_code' => $this->hsnCode,
            'preparation_time' => $this->preparationTime,
            'calories' => $this->calories,
            'protein' => $this->protein,
            'carbohydrates' => $this->carbohydrates,
            'fat' => $this->fat,
            'fiber' => $this->fiber,
            'sugar' => $this->sugar,
            'sodium' => $this->sodium,
            'price' => $this->price,
            'offer_price' => $this->offerPrice,
            'cost_price' => $this->costPrice,
            'tax_percentage' => $this->taxPercentage,
            'display_order' => $this->displayOrder,
            'availability_type' => $this->availabilityType,
            'availability_slots' => $this->availabilitySlots,
            'is_featured' => $this->isFeatured,
            'is_recommended' => $this->isRecommended,
            'is_new' => $this->isNew,
            'is_bestseller' => $this->isBestseller,
            'is_customizable' => $this->isCustomizable,
            'requires_preparation' => $this->requiresPreparation,
            'status' => $this->status,
            'remarks' => $this->remarks,
            'created_by' => $this->createdBy,
            'updated_by' => $this->updatedBy,
            'deleted_by' => $this->deletedBy,
        ];
    }
}
