<?php

declare(strict_types=1);

namespace App\DTOs\Supplier;

final class SupplierDTO
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $supplierName = null,
        public readonly ?string $supplierType = 'general',
        public readonly ?string $companyName = null,
        public readonly ?string $contactPerson = null,
        public readonly ?string $mobile = null,
        public readonly ?string $alternateMobile = null,
        public readonly ?string $email = null,
        public readonly ?string $website = null,
        public readonly ?string $gstNumber = null,
        public readonly ?string $panNumber = null,
        public readonly ?string $fssaiLicense = null,
        public readonly ?string $drugLicense = null,
        public readonly ?string $addressLine1 = null,
        public readonly ?string $addressLine2 = null,
        public readonly ?int $countryId = null,
        public readonly ?int $stateId = null,
        public readonly ?int $cityId = null,
        public readonly ?string $pincode = null,
        public readonly ?float $latitude = null,
        public readonly ?float $longitude = null,
        public readonly ?string $bankName = null,
        public readonly ?string $accountHolderName = null,
        public readonly ?string $accountNumber = null,
        public readonly ?string $ifscCode = null,
        public readonly ?string $branchName = null,
        public readonly float $creditLimit = 0,
        public readonly float $creditDays = 0,
        public readonly ?string $paymentTerms = 'Net 30',
        public readonly float $openingBalance = 0,
        public readonly float $currentBalance = 0,
        public readonly int $rating = 0,
        public readonly string $status = 'active',
        public readonly bool $isPreferred = false,
        public readonly ?string $remarks = null,
    ) {}

    public static function fromArray(array $data): self
    {
        return new self(
            id: isset($data['id']) ? (int) $data['id'] : null,
            supplierName: $data['supplier_name'] ?? $data['company_name'] ?? null,
            supplierType: $data['supplier_type'] ?? 'general',
            companyName: $data['company_name'] ?? null,
            contactPerson: $data['contact_person'] ?? null,
            mobile: $data['mobile'] ?? null,
            alternateMobile: $data['alternate_mobile'] ?? null,
            email: $data['email'] ?? null,
            website: $data['website'] ?? null,
            gstNumber: $data['gst_number'] ?? null,
            panNumber: $data['pan_number'] ?? null,
            fssaiLicense: $data['fssai_license'] ?? null,
            drugLicense: $data['drug_license'] ?? null,
            addressLine1: $data['address_line_1'] ?? null,
            addressLine2: $data['address_line_2'] ?? null,
            countryId: isset($data['country_id']) ? (int) $data['country_id'] : null,
            stateId: isset($data['state_id']) ? (int) $data['state_id'] : null,
            cityId: isset($data['city_id']) ? (int) $data['city_id'] : null,
            pincode: $data['pincode'] ?? null,
            latitude: isset($data['latitude']) ? (float) $data['latitude'] : null,
            longitude: isset($data['longitude']) ? (float) $data['longitude'] : null,
            bankName: $data['bank_name'] ?? null,
            accountHolderName: $data['account_holder_name'] ?? null,
            accountNumber: $data['account_number'] ?? null,
            ifscCode: $data['ifsc_code'] ?? null,
            branchName: $data['branch_name'] ?? null,
            creditLimit: (float) ($data['credit_limit'] ?? 0),
            creditDays: (float) ($data['credit_days'] ?? 0),
            paymentTerms: $data['payment_terms'] ?? 'Net 30',
            openingBalance: (float) ($data['opening_balance'] ?? 0),
            currentBalance: (float) ($data['current_balance'] ?? 0),
            rating: (int) ($data['rating'] ?? 0),
            status: $data['status'] ?? 'active',
            isPreferred: (bool) ($data['is_preferred'] ?? false),
            remarks: $data['remarks'] ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'supplier_name' => $this->supplierName,
            'supplier_type' => $this->supplierType,
            'company_name' => $this->companyName,
            'contact_person' => $this->contactPerson,
            'mobile' => $this->mobile,
            'alternate_mobile' => $this->alternateMobile,
            'email' => $this->email,
            'website' => $this->website,
            'gst_number' => $this->gstNumber,
            'pan_number' => $this->panNumber,
            'fssai_license' => $this->fssaiLicense,
            'drug_license' => $this->drugLicense,
            'address_line_1' => $this->addressLine1,
            'address_line_2' => $this->addressLine2,
            'country_id' => $this->countryId,
            'state_id' => $this->stateId,
            'city_id' => $this->cityId,
            'pincode' => $this->pincode,
            'latitude' => $this->latitude,
            'longitude' => $this->longitude,
            'bank_name' => $this->bankName,
            'account_holder_name' => $this->accountHolderName,
            'account_number' => $this->accountNumber,
            'ifsc_code' => $this->ifscCode,
            'branch_name' => $this->branchName,
            'credit_limit' => $this->creditLimit,
            'credit_days' => $this->creditDays,
            'payment_terms' => $this->paymentTerms,
            'opening_balance' => $this->openingBalance,
            'current_balance' => $this->currentBalance,
            'rating' => $this->rating,
            'status' => $this->status,
            'is_preferred' => $this->isPreferred,
            'remarks' => $this->remarks,
        ];
    }
}
