<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('countries')->delete();

        $now = now();
        $countries = [
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'IN',
                'iso3' => 'IND',
                'numeric_code' => '356',
                'phone_code' => '+91',
                'name' => 'India',
                'native_name' => 'India',
                'capital' => 'New Delhi',
                'currency_code' => 'INR',
                'currency_symbol' => '₹',
                'currency_name' => 'Indian Rupee',
                'emoji' => '🇮🇳',
                'emoji_unicode' => 'U+1F1EE U+1F1F3',
                'latitude' => 20.5937000,
                'longitude' => 78.9629000,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'nationality' => 'Indian',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 0,
                'is_default' => true,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'US',
                'iso3' => 'USA',
                'numeric_code' => '840',
                'phone_code' => '+1',
                'name' => 'United States',
                'native_name' => 'United States',
                'capital' => 'Washington D.C.',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'currency_name' => 'United States Dollar',
                'emoji' => '🇺🇸',
                'emoji_unicode' => 'U+1F1FA U+1F1F8',
                'latitude' => 37.0902000,
                'longitude' => -95.7129000,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'nationality' => 'American',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 1,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'GB',
                'iso3' => 'GBR',
                'numeric_code' => '826',
                'phone_code' => '+44',
                'name' => 'United Kingdom',
                'native_name' => 'United Kingdom',
                'capital' => 'London',
                'currency_code' => 'GBP',
                'currency_symbol' => '£',
                'currency_name' => 'Pound Sterling',
                'emoji' => '🇬🇧',
                'emoji_unicode' => 'U+1F1EC U+1F1E7',
                'latitude' => 55.3781000,
                'longitude' => -3.4360000,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'nationality' => 'British',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 2,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'CA',
                'iso3' => 'CAN',
                'numeric_code' => '124',
                'phone_code' => '+1',
                'name' => 'Canada',
                'native_name' => 'Canada',
                'capital' => 'Ottawa',
                'currency_code' => 'CAD',
                'currency_symbol' => 'C$',
                'currency_name' => 'Canadian Dollar',
                'emoji' => '🇨🇦',
                'emoji_unicode' => 'U+1F1E8 U+1F1E6',
                'latitude' => 56.1304000,
                'longitude' => -106.3468000,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'nationality' => 'Canadian',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 3,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'AU',
                'iso3' => 'AUS',
                'numeric_code' => '36',
                'phone_code' => '+61',
                'name' => 'Australia',
                'native_name' => 'Australia',
                'capital' => 'Canberra',
                'currency_code' => 'AUD',
                'currency_symbol' => 'A$',
                'currency_name' => 'Australian Dollar',
                'emoji' => '🇦🇺',
                'emoji_unicode' => 'U+1F1E6 U+1F1FA',
                'latitude' => -25.2744000,
                'longitude' => 133.7751000,
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'nationality' => 'Australian',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 4,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'DE',
                'iso3' => 'DEU',
                'numeric_code' => '276',
                'phone_code' => '+49',
                'name' => 'Germany',
                'native_name' => 'Germany',
                'capital' => 'Berlin',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_name' => 'Euro',
                'emoji' => '🇩🇪',
                'emoji_unicode' => 'U+1F1E9 U+1F1EA',
                'latitude' => 51.1657000,
                'longitude' => 10.4515000,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'nationality' => 'German',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 5,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'FR',
                'iso3' => 'FRA',
                'numeric_code' => '250',
                'phone_code' => '+33',
                'name' => 'France',
                'native_name' => 'France',
                'capital' => 'Paris',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_name' => 'Euro',
                'emoji' => '🇫🇷',
                'emoji_unicode' => 'U+1F1EB U+1F1F7',
                'latitude' => 46.2276000,
                'longitude' => 2.2137000,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'nationality' => 'French',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 6,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'JP',
                'iso3' => 'JPN',
                'numeric_code' => '392',
                'phone_code' => '+81',
                'name' => 'Japan',
                'native_name' => 'Japan',
                'capital' => 'Tokyo',
                'currency_code' => 'JPY',
                'currency_symbol' => '¥',
                'currency_name' => 'Japanese Yen',
                'emoji' => '🇯🇵',
                'emoji_unicode' => 'U+1F1EF U+1F1F5',
                'latitude' => 36.2048000,
                'longitude' => 138.2529000,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'nationality' => 'Japanese',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 7,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'CN',
                'iso3' => 'CHN',
                'numeric_code' => '156',
                'phone_code' => '+86',
                'name' => 'China',
                'native_name' => 'China',
                'capital' => 'Beijing',
                'currency_code' => 'CNY',
                'currency_symbol' => '¥',
                'currency_name' => 'Chinese Yuan',
                'emoji' => '🇨🇳',
                'emoji_unicode' => 'U+1F1E8 U+1F1F3',
                'latitude' => 35.8617000,
                'longitude' => 104.1954000,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'nationality' => 'Chinese',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 8,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'BR',
                'iso3' => 'BRA',
                'numeric_code' => '76',
                'phone_code' => '+55',
                'name' => 'Brazil',
                'native_name' => 'Brazil',
                'capital' => 'Brasilia',
                'currency_code' => 'BRL',
                'currency_symbol' => 'R$',
                'currency_name' => 'Brazilian Real',
                'emoji' => '🇧🇷',
                'emoji_unicode' => 'U+1F1E7 U+1F1F7',
                'latitude' => -14.2350000,
                'longitude' => -51.9253000,
                'region' => 'Americas',
                'subregion' => 'South America',
                'nationality' => 'Brazilian',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 9,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'ZA',
                'iso3' => 'ZAF',
                'numeric_code' => '710',
                'phone_code' => '+27',
                'name' => 'South Africa',
                'native_name' => 'South Africa',
                'capital' => 'Pretoria',
                'currency_code' => 'ZAR',
                'currency_symbol' => 'R',
                'currency_name' => 'South African Rand',
                'emoji' => '🇿🇦',
                'emoji_unicode' => 'U+1F1FF U+1F1E6',
                'latitude' => -30.5595000,
                'longitude' => 22.9375000,
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'nationality' => 'South African',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 10,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'AE',
                'iso3' => 'ARE',
                'numeric_code' => '784',
                'phone_code' => '+971',
                'name' => 'UAE',
                'native_name' => 'UAE',
                'capital' => 'Abu Dhabi',
                'currency_code' => 'AED',
                'currency_symbol' => 'د.إ',
                'currency_name' => 'United Arab Emirates Dirham',
                'emoji' => '🇦🇪',
                'emoji_unicode' => 'U+1F1E6 U+1F1EA',
                'latitude' => 23.4241000,
                'longitude' => 53.8478000,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'nationality' => 'Emirati',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 11,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'SG',
                'iso3' => 'SGP',
                'numeric_code' => '702',
                'phone_code' => '+65',
                'name' => 'Singapore',
                'native_name' => 'Singapore',
                'capital' => 'Singapore',
                'currency_code' => 'SGD',
                'currency_symbol' => 'S$',
                'currency_name' => 'Singapore Dollar',
                'emoji' => '🇸🇬',
                'emoji_unicode' => 'U+1F1F8 U+1F1EC',
                'latitude' => 1.3521000,
                'longitude' => 103.8198000,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'nationality' => 'Singaporean',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 12,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'SA',
                'iso3' => 'SAU',
                'numeric_code' => '682',
                'phone_code' => '+966',
                'name' => 'Saudi Arabia',
                'native_name' => 'Saudi Arabia',
                'capital' => 'Riyadh',
                'currency_code' => 'SAR',
                'currency_symbol' => '﷼',
                'currency_name' => 'Saudi Riyal',
                'emoji' => '🇸🇦',
                'emoji_unicode' => 'U+1F1F8 U+1F1E6',
                'latitude' => 23.8859000,
                'longitude' => 45.0792000,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'nationality' => 'Saudi',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 13,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'uuid' => Str::uuid()->toString(),
                'iso2' => 'NP',
                'iso3' => 'NPL',
                'numeric_code' => '524',
                'phone_code' => '+977',
                'name' => 'Nepal',
                'native_name' => 'Nepal',
                'capital' => 'Kathmandu',
                'currency_code' => 'NPR',
                'currency_symbol' => '₨',
                'currency_name' => 'Nepalese Rupee',
                'emoji' => '🇳🇵',
                'emoji_unicode' => 'U+1F1F3 U+1F1F5',
                'latitude' => 28.3949000,
                'longitude' => 84.1240000,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'nationality' => 'Nepalese',
                'flag_image' => null,
                'status' => 'active',
                'sort_order' => 14,
                'is_default' => false,
                'remarks' => null,
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
