<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CustomerAddressSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $countryId = DB::table('countries')->where('iso2', 'IN')->value('id');
        $stateId = DB::table('states')->where('name', 'Tamil Nadu')->value('id');
        $cityId = DB::table('cities')->where('name', 'Chennai')->value('id');

        $zoneIds = DB::table('delivery_zones')
            ->pluck('id', 'zone_code')
            ->toArray();

        $pincodeIds = DB::table('pincodes')
            ->pluck('id', 'pincode')
            ->toArray();

        $activeCustomers = DB::table('customers')
            ->where('status', 'active')
            ->orderBy('id', 'asc')
            ->limit(10)
            ->pluck('id')
            ->toArray();

        if (count($activeCustomers) < 10) {
            $this->command?->warn('Not enough active customers. Skipping CustomerAddressSeeder.');
            return;
        }

        $addresses = $this->getAddressData();
        $inserted = 0;

        foreach ($addresses as $index => $addr) {
            $customerId = $activeCustomers[$addr['customer_index']];

            $pincodeId = $pincodeIds[$addr['pincode_value']] ?? null;
            $deliveryZoneId = $zoneIds[$addr['zone_code']] ?? null;

            DB::table('customer_addresses')->insert([
                'uuid' => Str::uuid()->toString(),
                'customer_id' => $customerId,
                'country_id' => $countryId,
                'state_id' => $stateId,
                'city_id' => $cityId,
                'area_id' => null,
                'delivery_zone_id' => $deliveryZoneId,
                'pincode_id' => $pincodeId,
                'address_type' => $addr['address_type'],
                'house_no' => $addr['house_no'],
                'building_name' => $addr['building_name'],
                'floor' => $addr['floor'],
                'street' => $addr['street'],
                'landmark' => $addr['landmark'],
                'address_line_1' => $addr['address_line_1'],
                'address_line_2' => $addr['address_line_2'],
                'latitude' => $addr['latitude'],
                'longitude' => $addr['longitude'],
                'google_place_id' => null,
                'contact_person' => $addr['contact_person'],
                'contact_mobile' => $addr['contact_mobile'],
                'delivery_instruction' => $addr['delivery_instruction'],
                'is_default' => $addr['is_default'],
                'is_verified' => $addr['is_verified'],
                'status' => 'active',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => $now->copy()->subDays(mt_rand(1, 30)),
                'updated_at' => $now->copy()->subDays(mt_rand(0, 5)),
            ]);

            $inserted++;
        }

        $this->command?->info("{$inserted} customer addresses seeded successfully.");
    }

    private function getAddressData(): array
    {
        return [
            // Rahul Sharma (index 0) - 2 addresses
            [
                'customer_index' => 0,
                'address_type' => 'home',
                'house_no' => '42',
                'building_name' => 'Balaji Nagar',
                'floor' => '3',
                'street' => 'Velachery Main Road',
                'landmark' => 'Near Phoenix Mall',
                'address_line_1' => '42, Balaji Nagar, Velachery Main Road',
                'address_line_2' => 'Velachery',
                'latitude' => 12.9815,
                'longitude' => 80.2180,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Rahul Sharma',
                'contact_mobile' => '9876543210',
                'delivery_instruction' => 'Ring the doorbell twice',
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 0,
                'address_type' => 'office',
                'house_no' => '15',
                'building_name' => 'Tidel Park',
                'floor' => '7',
                'street' => 'Taramani Link Road',
                'landmark' => 'Opposite IIT Madras',
                'address_line_1' => '15, Tidel Park, Taramani Link Road',
                'address_line_2' => 'Taramani',
                'latitude' => 12.9870,
                'longitude' => 80.2433,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Rahul Sharma',
                'contact_mobile' => '9876543210',
                'delivery_instruction' => 'Leave at reception',
                'is_default' => false,
                'is_verified' => true,
            ],
            // Priya Rajan (index 1) - 2 addresses
            [
                'customer_index' => 1,
                'address_type' => 'home',
                'house_no' => '28',
                'building_name' => null,
                'floor' => null,
                'street' => 'Kabali Street, Besant Nagar',
                'landmark' => 'Near Elliot Beach',
                'address_line_1' => '28, Kabali Street, Besant Nagar',
                'address_line_2' => null,
                'latitude' => 12.9988,
                'longitude' => 80.2675,
                'pincode_value' => '600004',
                'zone_code' => 'SCZ',
                'contact_person' => 'Priya Rajan',
                'contact_mobile' => '9876543211',
                'delivery_instruction' => null,
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 1,
                'address_type' => 'pg',
                'house_no' => '12',
                'building_name' => 'Sri Lakshmi Ladies Hostel',
                'floor' => '2',
                'street' => 'LB Road',
                'landmark' => 'Near Adyar Bus Depot',
                'address_line_1' => '12, Sri Lakshmi Ladies Hostel, LB Road',
                'address_line_2' => 'Adyar',
                'latitude' => 13.0067,
                'longitude' => 80.2563,
                'pincode_value' => '600018',
                'zone_code' => 'SCZ',
                'contact_person' => 'Priya Rajan',
                'contact_mobile' => '9876543211',
                'delivery_instruction' => 'Ask for Priya at reception',
                'is_default' => false,
                'is_verified' => true,
            ],
            // Arun Kumar (index 2) - 3 addresses
            [
                'customer_index' => 2,
                'address_type' => 'home',
                'house_no' => '78',
                'building_name' => 'Sri Ganesh Flats',
                'floor' => '1',
                'street' => 'Velachery Tambaram High Road',
                'landmark' => 'Near Velachery Railway Station',
                'address_line_1' => '78, Sri Ganesh Flats, Velachery Tambaram High Road',
                'address_line_2' => 'Velachery',
                'latitude' => 12.9780,
                'longitude' => 80.2200,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Arun Kumar',
                'contact_mobile' => '9876543212',
                'delivery_instruction' => 'Call before delivery',
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 2,
                'address_type' => 'office',
                'house_no' => '5',
                'building_name' => 'Ascendas IT Park',
                'floor' => '12',
                'street' => 'Taramani Road',
                'landmark' => 'Near Tidel Park',
                'address_line_1' => '5, Ascendas IT Park, Taramani Road',
                'address_line_2' => 'Sholinganallur',
                'latitude' => 12.9010,
                'longitude' => 80.2279,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Arun Kumar',
                'contact_mobile' => '9876543212',
                'delivery_instruction' => 'Deliver to security desk',
                'is_default' => false,
                'is_verified' => false,
            ],
            [
                'customer_index' => 2,
                'address_type' => 'other',
                'house_no' => null,
                'building_name' => null,
                'floor' => null,
                'street' => null,
                'landmark' => 'Near T Nagar Post Office',
                'address_line_1' => 'Shop 3, Usman Road',
                'address_line_2' => 'T Nagar',
                'latitude' => 13.0418,
                'longitude' => 80.2341,
                'pincode_value' => '600002',
                'zone_code' => 'CCZ',
                'contact_person' => 'Arun Kumar',
                'contact_mobile' => '9876543212',
                'delivery_instruction' => null,
                'is_default' => false,
                'is_verified' => false,
            ],
            // Deepa Nair (index 3) - 2 addresses
            [
                'customer_index' => 3,
                'address_type' => 'home',
                'house_no' => '23',
                'building_name' => 'Narayana Apartments',
                'floor' => '4',
                'street' => 'Kodambakkam High Road',
                'landmark' => 'Near Pondy Bazaar',
                'address_line_1' => '23, Narayana Apartments, Kodambakkam High Road',
                'address_line_2' => 'T Nagar',
                'latitude' => 13.0418,
                'longitude' => 80.2305,
                'pincode_value' => '600002',
                'zone_code' => 'CCZ',
                'contact_person' => 'Deepa Nair',
                'contact_mobile' => '9876543213',
                'delivery_instruction' => 'Use back entrance',
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 3,
                'address_type' => 'office',
                'house_no' => '8',
                'building_name' => 'Vani Mahal',
                'floor' => '3',
                'street' => 'Kutchery Road',
                'landmark' => 'Near Kapaleeshwarar Temple',
                'address_line_1' => '8, Vani Mahal, Kutchery Road',
                'address_line_2' => 'Mylapore',
                'latitude' => 13.0339,
                'longitude' => 80.2676,
                'pincode_value' => '600004',
                'zone_code' => 'SCZ',
                'contact_person' => 'Deepa Nair',
                'contact_mobile' => '9876543213',
                'delivery_instruction' => 'Ring bell on 3rd floor',
                'is_default' => false,
                'is_verified' => true,
            ],
            // Meena Iyer (index 4) - 2 addresses
            [
                'customer_index' => 4,
                'address_type' => 'home',
                'house_no' => '56',
                'building_name' => null,
                'floor' => null,
                'street' => 'Mada Street, Mylapore',
                'landmark' => 'Near Mylapore Tank',
                'address_line_1' => '56, Mada Street, Mylapore',
                'address_line_2' => null,
                'latitude' => 13.0339,
                'longitude' => 80.2700,
                'pincode_value' => '600004',
                'zone_code' => 'SCZ',
                'contact_person' => 'Meena Iyer',
                'contact_mobile' => '9876543215',
                'delivery_instruction' => null,
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 4,
                'address_type' => 'pg',
                'house_no' => '3',
                'building_name' => 'Sunshine Paying Guest',
                'floor' => '2',
                'street' => 'Lattice Bridge Road',
                'landmark' => 'Near Adyar Gate',
                'address_line_1' => '3, Sunshine PG, Lattice Bridge Road',
                'address_line_2' => 'Adyar',
                'latitude' => 13.0010,
                'longitude' => 80.2565,
                'pincode_value' => '600018',
                'zone_code' => 'SCZ',
                'contact_person' => 'Meena Iyer',
                'contact_mobile' => '9876543215',
                'delivery_instruction' => 'Ask for Meena on 2nd floor',
                'is_default' => false,
                'is_verified' => false,
            ],
            // Kavitha Sundaram (index 5) - 3 addresses
            [
                'customer_index' => 5,
                'address_type' => 'home',
                'house_no' => '18',
                'building_name' => 'Nungambakkam Towers',
                'floor' => '5',
                'street' => 'Nungambakkam High Road',
                'landmark' => 'Near Gemini Flyover',
                'address_line_1' => '18, Nungambakkam Towers, Nungambakkam High Road',
                'address_line_2' => 'Nungambakkam',
                'latitude' => 13.0620,
                'longitude' => 80.2440,
                'pincode_value' => '600005',
                'zone_code' => 'CCZ',
                'contact_person' => 'Kavitha Sundaram',
                'contact_mobile' => '9876543217',
                'delivery_instruction' => null,
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 5,
                'address_type' => 'office',
                'house_no' => '10',
                'building_name' => 'SP Infocity',
                'floor' => '4',
                'street' => 'MTH Road',
                'landmark' => 'Near Anna Nagar Roundtana',
                'address_line_1' => '10, SP Infocity, MTH Road',
                'address_line_2' => 'Anna Nagar',
                'latitude' => 13.0850,
                'longitude' => 80.2101,
                'pincode_value' => '600005',
                'zone_code' => 'CCZ',
                'contact_person' => 'Kavitha Sundaram',
                'contact_mobile' => '9876543217',
                'delivery_instruction' => 'Deliver to front desk',
                'is_default' => false,
                'is_verified' => true,
            ],
            [
                'customer_index' => 5,
                'address_type' => 'other',
                'house_no' => null,
                'building_name' => null,
                'floor' => null,
                'street' => 'Purasawalkam High Road',
                'landmark' => 'Near DMS Office',
                'address_line_1' => 'Purasawalkam High Road',
                'address_line_2' => 'Purasawalkam',
                'latitude' => 13.0650,
                'longitude' => 80.2520,
                'pincode_value' => '600005',
                'zone_code' => 'CCZ',
                'contact_person' => 'Kavitha Sundaram',
                'contact_mobile' => '9876543217',
                'delivery_instruction' => null,
                'is_default' => false,
                'is_verified' => false,
            ],
            // Ravi Verma (index 6) - 2 addresses
            [
                'customer_index' => 6,
                'address_type' => 'home',
                'house_no' => '67',
                'building_name' => 'Kamakshi Nagar',
                'floor' => '2',
                'street' => 'Porur Main Road',
                'landmark' => 'Near Porur Lake',
                'address_line_1' => '67, Kamakshi Nagar, Porur Main Road',
                'address_line_2' => 'Porur',
                'latitude' => 13.0385,
                'longitude' => 80.1563,
                'pincode_value' => '600001',
                'zone_code' => 'CCZ',
                'contact_person' => 'Ravi Verma',
                'contact_mobile' => '9876543218',
                'delivery_instruction' => 'Call on arrival',
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 6,
                'address_type' => 'office',
                'house_no' => '2',
                'building_name' => 'Prince Info City',
                'floor' => '6',
                'street' => 'GST Road',
                'landmark' => 'Near Chromepet Signal',
                'address_line_1' => '2, Prince Info City, GST Road',
                'address_line_2' => 'Chromepet',
                'latitude' => 12.9516,
                'longitude' => 80.1413,
                'pincode_value' => '600001',
                'zone_code' => 'CCZ',
                'contact_person' => 'Ravi Verma',
                'contact_mobile' => '9876543218',
                'delivery_instruction' => null,
                'is_default' => false,
                'is_verified' => true,
            ],
            // Anitha Raj (index 7) - 3 addresses
            [
                'customer_index' => 7,
                'address_type' => 'home',
                'house_no' => '89',
                'building_name' => null,
                'floor' => null,
                'street' => 'Tambaram East',
                'landmark' => 'Near Tambaram Railway Station',
                'address_line_1' => '89, Tambaram East',
                'address_line_2' => 'Tambaram',
                'latitude' => 12.9249,
                'longitude' => 80.1000,
                'pincode_value' => '600001',
                'zone_code' => 'CCZ',
                'contact_person' => 'Anitha Raj',
                'contact_mobile' => '9876543219',
                'delivery_instruction' => null,
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 7,
                'address_type' => 'office',
                'house_no' => '22',
                'building_name' => 'Thiruvanmiyur Business Center',
                'floor' => '3',
                'street' => 'East Coast Road',
                'landmark' => 'Near Thiruvanmiyur Beach',
                'address_line_1' => '22, Thiruvanmiyur Business Center, ECR',
                'address_line_2' => 'Thiruvanmiyur',
                'latitude' => 12.9830,
                'longitude' => 80.2620,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Anitha Raj',
                'contact_mobile' => '9876543219',
                'delivery_instruction' => 'Leave with guard',
                'is_default' => false,
                'is_verified' => false,
            ],
            [
                'customer_index' => 7,
                'address_type' => 'pg',
                'house_no' => '5',
                'building_name' => 'Vivekananda Hostel',
                'floor' => '1',
                'street' => 'Royapuram 1st Street',
                'landmark' => 'Near Royapuram Beach',
                'address_line_1' => '5, Vivekananda Hostel, Royapuram 1st Street',
                'address_line_2' => 'Royapuram',
                'latitude' => 13.1100,
                'longitude' => 80.2950,
                'pincode_value' => '600021',
                'zone_code' => 'NCZ',
                'contact_person' => 'Anitha Raj',
                'contact_mobile' => '9876543219',
                'delivery_instruction' => null,
                'is_default' => false,
                'is_verified' => false,
            ],
            // Ganesh Padmanabhan (index 8) - 2 addresses
            [
                'customer_index' => 8,
                'address_type' => 'home',
                'house_no' => '101',
                'building_name' => 'OMR IT Corridor',
                'floor' => '8',
                'street' => 'Old Mahabalipuram Road',
                'landmark' => 'Near Sholinganallur Junction',
                'address_line_1' => '101, OMR IT Corridor, Old Mahabalipuram Road',
                'address_line_2' => 'Sholinganallur',
                'latitude' => 12.9010,
                'longitude' => 80.2279,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Ganesh Padmanabhan',
                'contact_mobile' => '9876543220',
                'delivery_instruction' => 'Use service lift',
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 8,
                'address_type' => 'office',
                'house_no' => '4',
                'building_name' => 'RMZ Millenia',
                'floor' => '15',
                'street' => 'Industrial Area',
                'landmark' => 'Near Perungudi',
                'address_line_1' => '4, RMZ Millenia, Industrial Area',
                'address_line_2' => 'Perungudi',
                'latitude' => 12.9650,
                'longitude' => 80.2400,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Ganesh Padmanabhan',
                'contact_mobile' => '9876543220',
                'delivery_instruction' => 'Deliver to cafeteria',
                'is_default' => false,
                'is_verified' => true,
            ],
            // Lakshmi Venkatesh (index 9) - 2 addresses
            [
                'customer_index' => 9,
                'address_type' => 'home',
                'house_no' => '22',
                'building_name' => 'Elliott Beach Residency',
                'floor' => '3',
                'street' => 'Thiruvanmiyur Main Road',
                'landmark' => 'Near Marundeeswarar Temple',
                'address_line_1' => '22, Elliott Beach Residency, Thiruvanmiyur Main Road',
                'address_line_2' => 'Thiruvanmiyur',
                'latitude' => 12.9830,
                'longitude' => 80.2620,
                'pincode_value' => '600041',
                'zone_code' => 'SCZ',
                'contact_person' => 'Lakshmi Venkatesh',
                'contact_mobile' => '9876543221',
                'delivery_instruction' => null,
                'is_default' => true,
                'is_verified' => true,
            ],
            [
                'customer_index' => 9,
                'address_type' => 'pg',
                'house_no' => '9',
                'building_name' => 'Lakshmi Residency',
                'floor' => '2',
                'street' => 'Adyar Main Road',
                'landmark' => 'Near Adyar Ananda Bhavan',
                'address_line_1' => '9, Lakshmi Residency, Adyar Main Road',
                'address_line_2' => 'Adyar',
                'latitude' => 13.0067,
                'longitude' => 80.2563,
                'pincode_value' => '600018',
                'zone_code' => 'SCZ',
                'contact_person' => 'Lakshmi Venkatesh',
                'contact_mobile' => '9876543221',
                'delivery_instruction' => 'Call before arriving',
                'is_default' => false,
                'is_verified' => true,
            ],
        ];
    }
}
