<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $customers = [
            [
                'first_name' => 'Rahul',
                'last_name' => 'Sharma',
                'email' => 'rahul.sharma@example.com',
                'phone' => '9876543210',
                'gender' => 'male',
                'date_of_birth' => '1995-03-15',
                'address_line_1' => '12, Anna Salai',
                'address_line_2' => 'Near LIC Building',
                'pincode' => '600002',
                'status' => 'active',
                'wallet_balance' => 1500.00,
                'referral_code' => 'RAHS0001',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Priya',
                'last_name' => 'Rajan',
                'email' => 'priya.rajan@example.com',
                'phone' => '9876543211',
                'gender' => 'female',
                'date_of_birth' => '1998-07-22',
                'address_line_1' => '45, Besant Nagar',
                'address_line_2' => null,
                'pincode' => '600090',
                'status' => 'active',
                'wallet_balance' => 3200.50,
                'referral_code' => 'PRIR0002',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Arun',
                'last_name' => 'Kumar',
                'email' => 'arun.kumar@example.com',
                'phone' => '9876543212',
                'gender' => 'male',
                'date_of_birth' => '1990-11-08',
                'address_line_1' => '78, Velachery Main Road',
                'address_line_2' => 'Balaji Nagar',
                'pincode' => '600042',
                'status' => 'active',
                'wallet_balance' => 750.00,
                'referral_code' => 'ARKU0003',
                'email_verified' => true,
                'phone_verified' => false,
            ],
            [
                'first_name' => 'Deepa',
                'last_name' => 'Nair',
                'email' => 'deepa.nair@example.com',
                'phone' => '9876543213',
                'gender' => 'female',
                'date_of_birth' => '1992-01-30',
                'address_line_1' => '23, T. Nagar',
                'address_line_2' => null,
                'pincode' => '600017',
                'status' => 'active',
                'wallet_balance' => 5000.00,
                'referral_code' => 'DEPN0004',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Vikram',
                'last_name' => 'Singh',
                'email' => 'vikram.singh@example.com',
                'phone' => '9876543214',
                'gender' => 'male',
                'date_of_birth' => '1988-06-12',
                'address_line_1' => '90, Adyar Bank Colony',
                'address_line_2' => null,
                'pincode' => '600020',
                'status' => 'inactive',
                'wallet_balance' => 0.00,
                'referral_code' => 'VIKS0005',
                'email_verified' => false,
                'phone_verified' => false,
            ],
            [
                'first_name' => 'Meena',
                'last_name' => 'Iyer',
                'email' => 'meena.iyer@example.com',
                'phone' => '9876543215',
                'gender' => 'female',
                'date_of_birth' => '1996-09-05',
                'address_line_1' => '56, Mylapore',
                'address_line_2' => 'Kutchery Road',
                'pincode' => '600004',
                'status' => 'active',
                'wallet_balance' => 2100.00,
                'referral_code' => 'MEIY0006',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Suresh',
                'last_name' => 'Babu',
                'email' => 'suresh.babu@example.com',
                'phone' => '9876543216',
                'gender' => 'male',
                'date_of_birth' => '1985-04-18',
                'address_line_1' => '34, Chromepet',
                'address_line_2' => 'GST Road',
                'pincode' => '600044',
                'status' => 'suspended',
                'is_blocked' => true,
                'block_reason' => 'Multiple payment failures',
                'wallet_balance' => 120.00,
                'referral_code' => 'SUBA0007',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Kavitha',
                'last_name' => 'Sundaram',
                'email' => 'kavitha.sundaram@example.com',
                'phone' => '9876543217',
                'gender' => 'female',
                'date_of_birth' => '1993-12-01',
                'address_line_1' => '18, Nungambakkam',
                'address_line_2' => null,
                'pincode' => '600034',
                'status' => 'active',
                'wallet_balance' => 890.00,
                'referral_code' => 'KASU0008',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Ravi',
                'last_name' => 'Verma',
                'email' => 'ravi.verma@example.com',
                'phone' => '9876543218',
                'gender' => 'male',
                'date_of_birth' => '1991-08-25',
                'address_line_1' => '67, Porur',
                'address_line_2' => 'Kamakshi Nagar',
                'pincode' => '600125',
                'status' => 'active',
                'wallet_balance' => 4500.00,
                'referral_code' => 'RAVE0009',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Anitha',
                'last_name' => 'Raj',
                'email' => 'anitha.raj@example.com',
                'phone' => '9876543219',
                'gender' => 'female',
                'date_of_birth' => '1997-02-14',
                'address_line_1' => '89, Tambaram',
                'address_line_2' => null,
                'pincode' => '600045',
                'status' => 'active',
                'wallet_balance' => 670.00,
                'referral_code' => 'ANRA0010',
                'email_verified' => false,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Ganesh',
                'last_name' => 'Padmanabhan',
                'email' => 'ganesh.p@example.com',
                'phone' => '9876543220',
                'gender' => 'male',
                'date_of_birth' => '1989-10-09',
                'address_line_1' => '101, Sholinganallur',
                'address_line_2' => 'OMR IT Corridor',
                'pincode' => '600119',
                'status' => 'active',
                'wallet_balance' => 12000.00,
                'referral_code' => 'GAPA0011',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Lakshmi',
                'last_name' => 'Venkatesh',
                'email' => 'lakshmi.v@example.com',
                'phone' => '9876543221',
                'gender' => 'female',
                'date_of_birth' => '1994-05-20',
                'address_line_1' => '22, Thiruvanmiyur',
                'address_line_2' => null,
                'pincode' => '600041',
                'status' => 'active',
                'wallet_balance' => 330.00,
                'referral_code' => 'LAVE0012',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Karthik',
                'last_name' => 'Subramanian',
                'email' => 'karthik.sub@example.com',
                'phone' => '9876543222',
                'gender' => 'male',
                'date_of_birth' => '1987-07-03',
                'address_line_1' => '55, Alwarpet',
                'address_line_2' => 'CPR Layout',
                'pincode' => '600018',
                'status' => 'active',
                'wallet_balance' => 2750.00,
                'referral_code' => 'KASU0013',
                'email_verified' => true,
                'phone_verified' => true,
            ],
            [
                'first_name' => 'Swathi',
                'last_name' => 'Mohan',
                'email' => 'swathi.mohan@example.com',
                'phone' => '9876543223',
                'gender' => 'female',
                'date_of_birth' => '1999-11-28',
                'address_line_1' => '71, Guindy',
                'address_line_2' => null,
                'pincode' => '600032',
                'status' => 'inactive',
                'wallet_balance' => 0.00,
                'referral_code' => 'SWMO0014',
                'email_verified' => false,
                'phone_verified' => false,
            ],
            [
                'first_name' => 'Prakash',
                'last_name' => 'Rajan',
                'email' => 'prakash.rajan@example.com',
                'phone' => '9876543224',
                'gender' => 'male',
                'date_of_birth' => '1986-03-17',
                'address_line_1' => '15, Ambattur',
                'address_line_2' => 'Industrial Estate',
                'pincode' => '600058',
                'status' => 'active',
                'wallet_balance' => 980.00,
                'referral_code' => 'PRRA0015',
                'email_verified' => true,
                'phone_verified' => true,
            ],
        ];

        $indiaId = DB::table('countries')->where('iso2', 'IN')->value('id');
        $tnId = DB::table('states')->where('name', 'Tamil Nadu')->value('id');
        $chennaiId = DB::table('cities')->where('name', 'Chennai')->value('id');

        foreach ($customers as $c) {
            DB::table('customers')->insert([
                'uuid' => Str::uuid()->toString(),
                'first_name' => $c['first_name'],
                'last_name' => $c['last_name'],
                'email' => $c['email'],
                'phone' => $c['phone'],
                'country_code' => '+91',
                'password' => Hash::make('Customer@123'),
                'gender' => $c['gender'],
                'date_of_birth' => $c['date_of_birth'],
                'address_line_1' => $c['address_line_1'],
                'address_line_2' => $c['address_line_2'] ?? null,
                'country_id' => $indiaId,
                'state_id' => $tnId,
                'city_id' => $chennaiId,
                'pincode' => $c['pincode'],
                'latitude' => 13.0827 + (mt_rand(-50, 50) / 1000),
                'longitude' => 80.2707 + (mt_rand(-50, 50) / 1000),
                'status' => $c['status'],
                'is_blocked' => $c['is_blocked'] ?? false,
                'block_reason' => $c['block_reason'] ?? null,
                'wallet_balance' => $c['wallet_balance'],
                'wallet_currency' => 'INR',
                'referral_code' => $c['referral_code'],
                'referred_by' => null,
                'email_verified' => $c['email_verified'],
                'phone_verified' => $c['phone_verified'],
                'last_login_at' => now()->subDays(mt_rand(0, 30)),
                'last_login_ip' => '192.168.1.' . mt_rand(1, 254),
                'last_login_device' => 'Android',
                'last_login_browser' => 'Chrome Mobile',
                'created_by' => null,
                'updated_by' => null,
                'deleted_by' => null,
                'created_at' => now()->subDays(mt_rand(1, 90)),
                'updated_at' => now()->subDays(mt_rand(0, 10)),
            ]);
        }

        $this->command->info('15 customers seeded successfully.');
    }
}
