<?php

declare(strict_types=1);

namespace App\DTOs\SubscriptionPlan;

final class SubscriptionPlanDTO
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $uuid = null,
        public readonly ?string $planCode = null,
        public readonly ?string $planName = null,
        public readonly ?string $slug = null,
        public readonly ?string $description = null,
        public readonly string $planType = 'monthly',
        public readonly string $billingCycle = 'monthly',
        public readonly int $durationDays = 30,
        public readonly ?int $mealCategoryId = null,
        public readonly int $kitchenId = 1,
        public readonly int $displayOrder = 0,
        public readonly float $price = 0,
        public readonly float $offerPrice = 0,
        public readonly float $securityDeposit = 0,
        public readonly float $taxPercentage = 0,
        public readonly float $deliveryCharge = 0,
        public readonly float $joiningFee = 0,
        public readonly float $minimumOrderAmount = 0,
        public readonly int $maximumSkipDays = 0,
        public readonly int $maximumPauseDays = 0,
        public readonly int $maximumActiveSubscriptions = 1,
        public readonly bool $mealSelectionEnabled = false,
        public readonly bool $customMealSelection = false,
        public readonly bool $defaultMealAssignment = true,
        public readonly bool $carryForwardSkippedMeals = false,
        public readonly bool $weekendDelivery = true,
        public readonly bool $holidayDelivery = false,
        public readonly bool $allowUpgrade = true,
        public readonly bool $allowDowngrade = false,
        public readonly bool $allowPause = true,
        public readonly bool $allowResume = true,
        public readonly bool $allowSkip = true,
        public readonly bool $allowCancel = true,
        public readonly bool $autoRenew = false,
        public readonly float $renewalDiscount = 0,
        public readonly int $trialDays = 0,
        public readonly bool $isPopular = false,
        public readonly bool $isRecommended = false,
        public readonly string $status = 'active',
        public readonly ?string $startsAt = null,
        public readonly ?string $endsAt = null,
        public readonly ?string $remarks = null,
        public readonly ?int $createdBy = null,
        public readonly ?int $updatedBy = null,
        public readonly ?int $deletedBy = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: isset($data['id']) ? (int) $data['id'] : null,
            uuid: $data['uuid'] ?? null,
            planCode: $data['plan_code'] ?? null,
            planName: $data['plan_name'] ?? null,
            slug: $data['slug'] ?? null,
            description: $data['description'] ?? null,
            planType: $data['plan_type'] ?? 'monthly',
            billingCycle: $data['billing_cycle'] ?? 'monthly',
            durationDays: isset($data['duration_days']) ? (int) $data['duration_days'] : 30,
            mealCategoryId: isset($data['meal_category_id']) ? (int) $data['meal_category_id'] : null,
            kitchenId: isset($data['kitchen_id']) ? (int) $data['kitchen_id'] : 1,
            displayOrder: isset($data['display_order']) ? (int) $data['display_order'] : 0,
            price: isset($data['price']) ? (float) $data['price'] : 0,
            offerPrice: isset($data['offer_price']) ? (float) $data['offer_price'] : 0,
            securityDeposit: isset($data['security_deposit']) ? (float) $data['security_deposit'] : 0,
            taxPercentage: isset($data['tax_percentage']) ? (float) $data['tax_percentage'] : 0,
            deliveryCharge: isset($data['delivery_charge']) ? (float) $data['delivery_charge'] : 0,
            joiningFee: isset($data['joining_fee']) ? (float) $data['joining_fee'] : 0,
            minimumOrderAmount: isset($data['minimum_order_amount']) ? (float) $data['minimum_order_amount'] : 0,
            maximumSkipDays: isset($data['maximum_skip_days']) ? (int) $data['maximum_skip_days'] : 0,
            maximumPauseDays: isset($data['maximum_pause_days']) ? (int) $data['maximum_pause_days'] : 0,
            maximumActiveSubscriptions: isset($data['maximum_active_subscriptions']) ? (int) $data['maximum_active_subscriptions'] : 1,
            mealSelectionEnabled: (bool) ($data['meal_selection_enabled'] ?? false),
            customMealSelection: (bool) ($data['custom_meal_selection'] ?? false),
            defaultMealAssignment: (bool) ($data['default_meal_assignment'] ?? true),
            carryForwardSkippedMeals: (bool) ($data['carry_forward_skipped_meals'] ?? false),
            weekendDelivery: (bool) ($data['weekend_delivery'] ?? true),
            holidayDelivery: (bool) ($data['holiday_delivery'] ?? false),
            allowUpgrade: (bool) ($data['allow_upgrade'] ?? true),
            allowDowngrade: (bool) ($data['allow_downgrade'] ?? false),
            allowPause: (bool) ($data['allow_pause'] ?? true),
            allowResume: (bool) ($data['allow_resume'] ?? true),
            allowSkip: (bool) ($data['allow_skip'] ?? true),
            allowCancel: (bool) ($data['allow_cancel'] ?? true),
            autoRenew: (bool) ($data['auto_renew'] ?? false),
            renewalDiscount: isset($data['renewal_discount']) ? (float) $data['renewal_discount'] : 0,
            trialDays: isset($data['trial_days']) ? (int) $data['trial_days'] : 0,
            isPopular: (bool) ($data['is_popular'] ?? false),
            isRecommended: (bool) ($data['is_recommended'] ?? false),
            status: $data['status'] ?? 'active',
            startsAt: $data['starts_at'] ?? null,
            endsAt: $data['ends_at'] ?? null,
            remarks: $data['remarks'] ?? null,
            createdBy: isset($data['created_by']) ? (int) $data['created_by'] : null,
            updatedBy: isset($data['updated_by']) ? (int) $data['updated_by'] : null,
            deletedBy: isset($data['deleted_by']) ? (int) $data['deleted_by'] : null,
        );
    }

    public static function fromModel($model): self
    {
        return new self(
            id: $model->id,
            uuid: $model->uuid,
            planCode: $model->plan_code,
            planName: $model->plan_name,
            slug: $model->slug,
            description: $model->description,
            planType: $model->plan_type,
            billingCycle: $model->billing_cycle,
            durationDays: $model->duration_days,
            mealCategoryId: $model->meal_category_id,
            kitchenId: $model->kitchen_id,
            displayOrder: $model->display_order,
            price: (float) $model->price,
            offerPrice: (float) $model->offer_price,
            securityDeposit: (float) $model->security_deposit,
            taxPercentage: (float) $model->tax_percentage,
            deliveryCharge: (float) $model->delivery_charge,
            joiningFee: (float) $model->joining_fee,
            minimumOrderAmount: (float) $model->minimum_order_amount,
            maximumSkipDays: $model->maximum_skip_days,
            maximumPauseDays: $model->maximum_pause_days,
            maximumActiveSubscriptions: $model->maximum_active_subscriptions,
            mealSelectionEnabled: $model->meal_selection_enabled,
            customMealSelection: $model->custom_meal_selection,
            defaultMealAssignment: $model->default_meal_assignment,
            carryForwardSkippedMeals: $model->carry_forward_skipped_meals,
            weekendDelivery: $model->weekend_delivery,
            holidayDelivery: $model->holiday_delivery,
            allowUpgrade: $model->allow_upgrade,
            allowDowngrade: $model->allow_downgrade,
            allowPause: $model->allow_pause,
            allowResume: $model->allow_resume,
            allowSkip: $model->allow_skip,
            allowCancel: $model->allow_cancel,
            autoRenew: $model->auto_renew,
            renewalDiscount: (float) $model->renewal_discount,
            trialDays: $model->trial_days,
            isPopular: $model->is_popular,
            isRecommended: $model->is_recommended,
            status: $model->status,
            startsAt: $model->starts_at?->format('Y-m-d H:i:s'),
            endsAt: $model->ends_at?->format('Y-m-d H:i:s'),
            remarks: $model->remarks,
            createdBy: $model->created_by,
            updatedBy: $model->updated_by,
            deletedBy: $model->deleted_by,
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'uuid' => $this->uuid,
            'plan_code' => $this->planCode,
            'plan_name' => $this->planName,
            'slug' => $this->slug,
            'description' => $this->description,
            'plan_type' => $this->planType,
            'billing_cycle' => $this->billingCycle,
            'duration_days' => $this->durationDays,
            'meal_category_id' => $this->mealCategoryId,
            'kitchen_id' => $this->kitchenId,
            'display_order' => $this->displayOrder,
            'price' => $this->price,
            'offer_price' => $this->offerPrice,
            'security_deposit' => $this->securityDeposit,
            'tax_percentage' => $this->taxPercentage,
            'delivery_charge' => $this->deliveryCharge,
            'joining_fee' => $this->joiningFee,
            'minimum_order_amount' => $this->minimumOrderAmount,
            'maximum_skip_days' => $this->maximumSkipDays,
            'maximum_pause_days' => $this->maximumPauseDays,
            'maximum_active_subscriptions' => $this->maximumActiveSubscriptions,
            'meal_selection_enabled' => $this->mealSelectionEnabled,
            'custom_meal_selection' => $this->customMealSelection,
            'default_meal_assignment' => $this->defaultMealAssignment,
            'carry_forward_skipped_meals' => $this->carryForwardSkippedMeals,
            'weekend_delivery' => $this->weekendDelivery,
            'holiday_delivery' => $this->holidayDelivery,
            'allow_upgrade' => $this->allowUpgrade,
            'allow_downgrade' => $this->allowDowngrade,
            'allow_pause' => $this->allowPause,
            'allow_resume' => $this->allowResume,
            'allow_skip' => $this->allowSkip,
            'allow_cancel' => $this->allowCancel,
            'auto_renew' => $this->autoRenew,
            'renewal_discount' => $this->renewalDiscount,
            'trial_days' => $this->trialDays,
            'is_popular' => $this->isPopular,
            'is_recommended' => $this->isRecommended,
            'status' => $this->status,
            'starts_at' => $this->startsAt,
            'ends_at' => $this->endsAt,
            'remarks' => $this->remarks,
            'created_by' => $this->createdBy,
            'updated_by' => $this->updatedBy,
            'deleted_by' => $this->deletedBy,
        ];
    }
}
