<?php

declare(strict_types=1);

namespace App\DTOs\Kitchen;

final class KitchenDTO
{
    public function __construct(
        public readonly ?int $id = null,
        public readonly ?string $uuid = null,
        public readonly ?string $kitchenCode = null,
        public readonly ?string $name = null,
        public readonly ?string $description = null,
        public readonly ?string $kitchenType = 'main_kitchen',
        public readonly ?string $managerName = null,
        public readonly ?string $managerMobile = null,
        public readonly ?string $managerEmail = null,
        public readonly ?int $countryId = null,
        public readonly ?int $stateId = null,
        public readonly ?int $cityId = null,
        public readonly ?int $areaId = null,
        public readonly ?int $deliveryZoneId = null,
        public readonly ?string $addressLine1 = null,
        public readonly ?string $addressLine2 = null,
        public readonly ?string $landmark = null,
        public readonly ?float $latitude = null,
        public readonly ?float $longitude = null,
        public readonly ?string $openingTime = null,
        public readonly ?string $closingTime = null,
        public readonly ?string $preparationStartTime = null,
        public readonly ?string $acceptOrderStartTime = null,
        public readonly ?string $acceptOrderEndTime = null,
        public readonly ?int $dailyCapacity = null,
        public readonly ?int $maximumOrders = null,
        public readonly ?string $emergencyContact = null,
        public readonly ?string $licenseNumber = null,
        public readonly ?string $fssaiNumber = null,
        public readonly ?string $gstNumber = null,
        public readonly ?string $logo = null,
        public readonly ?string $status = 'active',
        public readonly bool $isDefault = false,
        public readonly ?string $remarks = null,
        public readonly ?int $createdBy = null,
        public readonly ?int $updatedBy = null,
        public readonly ?int $deletedBy = null,
    ) {
    }

    public static function fromArray(array $data): self
    {
        return new self(
            id: isset($data['id']) ? (int) $data['id'] : null,
            uuid: $data['uuid'] ?? null,
            kitchenCode: $data['kitchen_code'] ?? null,
            name: $data['name'] ?? null,
            description: $data['description'] ?? null,
            kitchenType: $data['kitchen_type'] ?? 'main_kitchen',
            managerName: $data['manager_name'] ?? null,
            managerMobile: $data['manager_mobile'] ?? null,
            managerEmail: $data['manager_email'] ?? null,
            countryId: isset($data['country_id']) ? (int) $data['country_id'] : null,
            stateId: isset($data['state_id']) ? (int) $data['state_id'] : null,
            cityId: isset($data['city_id']) ? (int) $data['city_id'] : null,
            areaId: isset($data['area_id']) ? (int) $data['area_id'] : null,
            deliveryZoneId: isset($data['delivery_zone_id']) ? (int) $data['delivery_zone_id'] : null,
            addressLine1: $data['address_line_1'] ?? null,
            addressLine2: $data['address_line_2'] ?? null,
            landmark: $data['landmark'] ?? null,
            latitude: isset($data['latitude']) ? (float) $data['latitude'] : null,
            longitude: isset($data['longitude']) ? (float) $data['longitude'] : null,
            openingTime: $data['opening_time'] ?? null,
            closingTime: $data['closing_time'] ?? null,
            preparationStartTime: $data['preparation_start_time'] ?? null,
            acceptOrderStartTime: $data['accept_order_start_time'] ?? null,
            acceptOrderEndTime: $data['accept_order_end_time'] ?? null,
            dailyCapacity: isset($data['daily_capacity']) ? (int) $data['daily_capacity'] : null,
            maximumOrders: isset($data['maximum_orders']) ? (int) $data['maximum_orders'] : null,
            emergencyContact: $data['emergency_contact'] ?? null,
            licenseNumber: $data['license_number'] ?? null,
            fssaiNumber: $data['fssai_number'] ?? null,
            gstNumber: $data['gst_number'] ?? null,
            logo: $data['logo'] ?? null,
            status: $data['status'] ?? 'active',
            isDefault: (bool) ($data['is_default'] ?? false),
            remarks: $data['remarks'] ?? null,
            createdBy: isset($data['created_by']) ? (int) $data['created_by'] : null,
            updatedBy: isset($data['updated_by']) ? (int) $data['updated_by'] : null,
            deletedBy: isset($data['deleted_by']) ? (int) $data['deleted_by'] : null,
        );
    }

    public function toArray(): array
    {
        return [
            'id' => $this->id,
            'uuid' => $this->uuid,
            'kitchen_code' => $this->kitchenCode,
            'name' => $this->name,
            'description' => $this->description,
            'kitchen_type' => $this->kitchenType,
            'manager_name' => $this->managerName,
            'manager_mobile' => $this->managerMobile,
            'manager_email' => $this->managerEmail,
            'country_id' => $this->countryId,
            'state_id' => $this->stateId,
            'city_id' => $this->cityId,
            'area_id' => $this->areaId,
            'delivery_zone_id' => $this->deliveryZoneId,
            'address_line_1' => $this->addressLine1,
            'address_line_2' => $this->addressLine2,
            'landmark' => $this->landmark,
            'latitude' => $this->latitude,
            'longitude' => $this->longitude,
            'opening_time' => $this->openingTime,
            'closing_time' => $this->closingTime,
            'preparation_start_time' => $this->preparationStartTime,
            'accept_order_start_time' => $this->acceptOrderStartTime,
            'accept_order_end_time' => $this->acceptOrderEndTime,
            'daily_capacity' => $this->dailyCapacity,
            'maximum_orders' => $this->maximumOrders,
            'emergency_contact' => $this->emergencyContact,
            'license_number' => $this->licenseNumber,
            'fssai_number' => $this->fssaiNumber,
            'gst_number' => $this->gstNumber,
            'logo' => $this->logo,
            'status' => $this->status,
            'is_default' => $this->isDefault,
            'remarks' => $this->remarks,
            'created_by' => $this->createdBy,
            'updated_by' => $this->updatedBy,
            'deleted_by' => $this->deletedBy,
        ];
    }
}
